import React from 'react';

import Navbar from "@/_components/Navbar";
import Footer from "@/_components/Footer";
import Head from "next/head";

const PUBLIC_URL = process.env.PUBLIC_URL ?? process.env.NEXT_PUBLIC_URL;

interface ILayoutPage {
  children: any;
}

const Layout: React.FunctionComponent<ILayoutPage> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={PUBLIC_URL +"/favicon.ico"} />
      </Head>

      <Navbar />

      <main>
        {children}
      </main>

      <Footer />
    </>
  );
};

export default Layout;
