import { Html, Head, Main, NextScript } from "next/document";
import React from "react";
const PUBLIC_URL = process.env.PUBLIC_URL ?? process.env.NEXT_PUBLIC_URL;

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        {/*<title>Create Next App</title>*/}
        <meta name="description" content="Generated by create next app" />
        {/*<meta name="viewport" content="width=device-width, initial-scale=1" />*/}
        <link rel="icon" href={PUBLIC_URL +"/favicon.ico"} />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
